import Constants from "expo-constants";
import { avatar, maps, notFound } from "../config/images";

const extra = Constants.expoConfig.extra;
export const Config = {
  app_name: Constants.expoConfig.name,
  app_version: Constants.expoConfig.version,
  base_url: extra.base_url,
  base_url_kores: extra.base_url_kores,
  base_url_auth: extra.base_url_auth,
  base_url_cuti: extra.base_url_cuti,
  base_url_helpdesk: extra.base_url_helpdesk,
  upgrade_url: extra.upgrade_url,
  notFound: notFound[extra.id],
  oneSignalAppId: extra.oneSignalAppId,
  maps: maps[extra.id],
  avatar: avatar[extra.id],
  statusbarAuth: extra.statusBarAuth,
  statusbarAuthenticated: extra.statusBarAuthtenticated,
  editInpro: extra.editInpro,
  todo: extra.todo,
  labelTodo: extra.labelTodo,
  loginSSO: extra.loginSSO,
  termOfUse: extra.termOfUse,
  prefix: extra.prefix,
  api: {
    auth: extra.api.auth,
    dashboard: extra.api.dashboard,
    getTermofuse: extra.api.getTermofuse,
    getVersionAndroid: extra.api.getVersionAndroid,
    getVersionIos: extra.api.getVersionIos,
    signOutAPI: extra.api.signOutAPI,
    searchglobal: extra.api.searchglobal,

    profile: extra.api.profile,
    profiletitle: extra.api.profiletitle,
    checkdevice: extra.api.checkdevice,
    switchoffdevice: extra.api.switchoffdevice,

    agendain: extra.api.agendain,
    agendaininternal: extra.api.agendaininternal,
    agendainsearch: extra.api.agendainsearch,
    agendainunread: extra.api.agendainunread,
    agendainunreadsearch: extra.api.agendainunreadsearch,
    agendainfilter: extra.api.agendainfilter,
    agendainbyid: extra.api.agendainbyid,
    agendainread: extra.api.agendainread,
    agendainlog: extra.api.agendainlog,

    dispoaction: extra.api.dispoaction,
    agendadispo: extra.api.agendadispo,
    agendadisposearch: extra.api.agendadisposearch,
    agendadispounread: extra.api.agendadispounread,
    agendadispounreadsearch: extra.api.agendadispounreadsearch,
    agendadispobyid: extra.api.agendadispobyid,
    agendadisporead: extra.api.agendadisporead,
    agendadispolog: extra.api.agendadispolog,
    agendamydispo: extra.api.agendamydispo,
    agendamydisposearch: extra.api.agendamydisposearch,

    agendaout: extra.api.agendaout,
    agendaoutsearch: extra.api.agendaoutsearch,
    agendaoutbyid: extra.api.agendaoutbyid,
    agendaoutlog: extra.api.agendaoutlog,

    todooverdue: extra.api.todooverdue,
    todonextweek: extra.api.todonextweek,
    todotoday: extra.api.todotoday,
    todosearch: extra.api.todosearch,
    todobyid: extra.api.todobyid,
    todomarkcomplete: extra.api.todomarkcomplete,
    todocomment: extra.api.todocomment,
    todocommentreply: extra.api.todocommentreply,

    delegationassigned: extra.api.delegationassigned,
    delegation: extra.api.delegation,
    delegationsearch: extra.api.delegationsearch,
    delegationbyid: extra.api.delegationbyid,
    delegationactive: extra.api.delegationactive,
    delegationdeactivate: extra.api.delegationdeactivate,
    createdelegation: extra.api.createdelegation,
    checkActiveDelegation: extra.api.checkActiveDelegation,

    secretaryassigned: extra.api.secretaryassigned,
    editSecretary: extra.api.editSecretary,
    secretary: extra.api.secretary,
    secretarysearch: extra.api.secretarysearch,
    secretarybyid: extra.api.secretarybyid,
    secretarydeactivate: extra.api.secretarydeactivate,
    secretaryactive: extra.api.secretaryactive,
    createsecretary: extra.api.createsecretary,
    checksecretary: extra.api.checksecretary,

    needfollowup: extra.api.needfollowup,
    needfollowupsearch: extra.api.needfollowupsearch,
    tracking: extra.api.tracking,
    trackingsearch: extra.api.trackingsearch,
    scanlog: extra.api.scanlog,
    scanlogsearch: extra.api.scanlogsearch,
    scanlogbyid: extra.api.scanlogbyid,
    lettersbyid: extra.api.lettersbyid,
    lettersubmit: extra.api.lettersubmit,
    letteridsave: extra.api.letteridsave,
    letteridapprove: extra.api.letteridapprove,
    letterbulkapprove: extra.api.letterbulkapprove,
    letteridfinish: extra.api.letteridfinish,
    letteridreturn: extra.api.letteridreturn,
    letteridreturntokonseptor: extra.api.letteridreturntokonseptor,
    letteridreject: extra.api.letteridreject,
    verifytitleprofile: extra.api.verifytitleprofile,

    listDraft: extra.api.listDraft,
    listComposer: extra.api.listComposer,
    listTemplates: extra.api.listTemplates,
    receivedLetter: extra.api.receivedLetter,
    preview: extra.api.preview,

    kmtree: extra.api.kmtree,
    kmSearch: extra.api.kmSearch,
    employee: extra.api.employee,
    employeeSearch: extra.api.employeeSearch,
    unit: extra.api.unit,
    divisionbyunitid: extra.api.divisionbyunitid,
    titlebydivisionid: extra.api.titlebydivisionid,
    parabydivisionid: extra.api.parabydivisionid,
    titleSearch: extra.api.titleSearch,
    divisionList: extra.api.divisionList,
    personallist: extra.api.personallist,
    personaladd: extra.api.personaladd,
    personaldel: extra.api.personaldel,
    subordinate: extra.api.subordinate,

    attachmentshow: extra.api.attachmentshow,

    listArchiveIn: extra.api.listArchiveIn,
    listArchiveOut: extra.api.listArchiveOut,
    listArchiveCanceled: extra.api.listArchiveCanceled,
    listArchiveDisposition: extra.api.listArchiveDisposition,
    listArchiveMyDisposition: extra.api.listArchiveMyDisposition,
    listArchiveTodo: extra.api.listArchiveTodo,
    letterShow: extra.api.letterShow,

    searchEmailSign: extra.api.searchEmailSign,
    sendPenandatangan: extra.api.sendPenandatangan,
    docSigned: extra.api.docSigned,
    postDisposition: extra.api.postDisposition,
    downloadDisposisi: extra.api.downloadDisposisi,

    postForward: extra.api.postForward,

    cekDays: extra.api.cekDays,
    saveDraftBg: extra.api.saveDraftBg,
    submitBg: extra.api.submitBg,
    attachmentBg: extra.api.attachmentBg,
    data_config: extra.api.data_config,
    info_user: extra.api.info_user,
    prebg: extra.api.prebg,
    bankbg: extra.api.bankbg,
    dataRevisiPermohonanId: extra.api.dataRevisiPermohonanId,

    searchGlobal: extra.api.searchGlobal,

    adddevice: extra.api.adddevice,
    listdevice: extra.api.listdevice,
    getdevicebyhash: extra.api.getdevicebyhash,
    getdevicebyid: extra.api.getdevicebyid,
    deletedevice: extra.api.deletedevice,
    deletealldevice: extra.api.deletealldevice,

    postcomment: extra.api.postcomment,
    replycomment: extra.api.replycomment,

    getdefaultapprovers: extra.api.getdefaultapprovers,
    profileapprovers: extra.api.profileapprovers,
    profileapproversbyid: extra.api.profileapproversbyid,
    profileapproversdefault: extra.api.profileapproversdefault,
    profileapproversdel: extra.api.profileapproversdel,
    profileapproverssave: extra.api.profileapproverssave,
  },
};
